apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qtpn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qtpn
    app.kubernetes.io/part-of: adkaplan-demo
  name: devfile-sample-qtpn
  namespace: adkaplan-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-qtpn
    weight: null
status: {}
